spring.datasource.url=jdbc:mysql://localhost:3306/bmb_db
spring.datasource.username=root
spring.datasource.password=8291184587

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect